language: php

php:
  - 7
  - 7.1
  - nightly
  - hhvm

env:
  - PACKAGES='symfony/symfony=2.8.*'
  - PACKAGES='symfony/symfony=3.1.*'
  - PACKAGES='symfony/symfony=3.2.*'
  - PACKAGES='symfony/symfony=~3.3@dev'

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

before_install:
  - travis_retry composer self-update

install:
  - composer require --no-update ${PACKAGES}
  - composer --prefer-source install

script:
  - mkdir -p build
  - vendor/bin/phpunit --colors -c phpunit.xml
